application: timx-monitoring
version: 2
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /.*
  script: main.app
- url: /public
  static_dir: public

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
